### ISSUE TITLE
Not working on tunein.com

### ISSUE THREAD

**Issue by LL25255252** [abba23/mute-sites-by-default#3]
for example - https://tunein.com/radio/100hitz---Hip-Hop-s111385/

I put this radio station on one of my pinned tab.
All pinned tabs are loaded when the browser starts including this tab which starts to play unmuted even if I install your addon.

So can you please make your addon work on this  tunein.com site ?

BTW - I know I can change browser.sessionstore.restore_pinned_tabs_on_demand to True but I want one of my other pinned to load at start.

Thanks in advance.
Win 7 x64
Waterfox 56.2.7.1 (64-bit)

**Comment by abba23** [comment]
I just tried your example with Firefox (65.0.2) and it was muted.

* Have you tried it with Firefox instead of Waterfox? I'm not sure how the two differ exactly, but I guess this could be a bug resulting from the changes they apply to Waterfox.

* Are you sure the site isn't on your whitelist?

* Is your example the only site it doesn't work with or do you have the same problem with other sites too?

**Comment by LL25255252** [comment]
@abba23, sorry for wasting your time...Today everything is OK.
I'll keep monitoring...maybe it happens in some particular situation. If so I promise to try to reproduce it and re-open this issue again.
