### ISSUE TITLE
Suggestions regarding the whitelist/blacklist of sites

### ISSUE THREAD

**Issue by LL25255252** [abba23/mute-sites-by-default#4]
I need this addon to mute only a few sites (like tunein.com) so it would be great for me if you add an option to use a blacklist instead of the current whitelist.

If you do decide not add a blacklist an option to quickly add a site from the current tab to the whitelist (instead of opening the addons-Manager and pasting the URL) would be very helpful.

Ticking the "options" checkbox helps in adding to the whitelist  but the downside is that every click on the mute icon of a tab that I do want to mute (like my  tunein.com tab) adds it to the whitelist.

Thanks in advance.

**Comment by abba23** [comment]
>I need this addon to mute only a few sites (like tunein.com) so it would be great for me if you add an option to use a blacklist instead of the current whitelist.

I don't really like the idea of a blacklist, because it pretty much turns the whole idea of this addon on its head. The purpose is to mute all sites by default (as implied by the name), not to mute some specific sites and have everything else unmuted by default. You might want to use a different addon if that's what you're really trying to do.

>If you do decide not add a blacklist an option to quickly add a site from the current tab to the whitelist (instead of opening the addons-Manager and pasting the URL) would be very helpful.

That might be a good compromise. Adding a button with that functionality to the toolbar could be useful for some users I suppose.
